apiVersion: v1
kind: Service
metadata:
  name: service-lamp-app
  labels:
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    name: lamp-app-apache-php-pod