apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    name: lamp-app-db-pod