apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: lamp-app
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: lamp-app
    name: lamp-app-db-pod