apiVersion: v1
kind: Service
metadata:
  name: service-lamp-app
  labels:
    app: lamp-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: lamp-app